### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by JuBan1**

### CODE REVIEW

**Comment by danieleds** [comment]
I'm afraid this won't work... Travis provides containers with Ubuntu 14.04, where libqt5webengine5-dev is not available.

**Comment by JuBan1** [comment]
Humm, I guess we can't use a script to install the prepacked binary you posted in the other thread?

**Comment by danieleds** [comment]
It might be possible. I'm just wondering if we must install *all* the packages from the ppa or we can get just qtwebengine and keep downloading the other stuff from the main repos.

Another thing: I'm not sure if that ppa includes dev packages.

**Comment by danieleds** [comment]
As a better alternative we can use Docker: https://docs.travis-ci.com/user/docker/
I'll set up a docker container when it will be time to merge to master.

**Pull request merged**
